import crypto from 'node:crypto';
import { payloadHash } from './evidence.mjs';

function digest(value){return crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');}
export function buildReviewPackage(input={}){const basis={taskId:input.taskId,changeFingerprint:input.changeFingerprint,goal:input.goal,acceptance:input.acceptance??[],qualityContracts:input.qualityContracts??[],canonicalExemplars:input.canonicalExemplars??[],evidenceSummary:input.evidenceSummary??{},specImpact:input.specImpact??null,specTraceability:input.specTraceability??null,specConsistency:input.specConsistency??null,residualRisks:input.residualRisks??[]};const pack={schemaVersion:4,id:input.id??`review-package-${crypto.randomUUID()}`,...basis,basisFingerprint:digest(basis),createdAt:input.createdAt??new Date().toISOString()};pack.packageFingerprint=payloadHash(pack);return pack;}
export function createReviewRecord(input={}){const record={schemaVersion:4,id:input.id??`review-${crypto.randomUUID()}`,kind:input.kind??'self',subject:{taskId:input.taskId,changeFingerprint:input.changeFingerprint,packageFingerprint:input.packageFingerprint},implementer:input.implementer??null,reviewer:input.reviewer??null,decision:input.decision??'advisory',findings:input.findings??[],createdAt:input.createdAt??new Date().toISOString()};record.payloadHash=payloadHash(record);return record;}
export function validateReviewRecord(record,context={}){const errors=[];if(record?.schemaVersion!==4)errors.push('Review Schema 必须是 4');if(record?.payloadHash!==payloadHash(record))errors.push('Review Payload Hash 无效');if(record?.subject?.taskId!==context.taskId)errors.push('Review 不属于当前 Task');if(record?.subject?.changeFingerprint!==context.changeFingerprint)errors.push('Review 不属于当前 ChangeSet');if(context.packageFingerprint&&record?.subject?.packageFingerprint!==context.packageFingerprint)errors.push('Review Package 已过期');if(context.packageCreatedAt&&Date.parse(record?.createdAt??0)<Date.parse(context.packageCreatedAt))errors.push('Review 早于 Review Package');if(!['passed','failed','advisory'].includes(record?.decision))errors.push('Review Decision 无效');if(!Array.isArray(record?.findings))errors.push('Review Findings 必须是数组');
 if(record?.kind==='independent-agent'){if(!record.reviewer?.actor||!record.reviewer?.session||!record.reviewer?.provenance)errors.push('Independent Review 缺少 Actor、Session 或 Provenance');if(!record.implementer?.actor||!record.implementer?.session)errors.push('Independent Review 缺少 Implementer');if(record.implementer?.actor===record.reviewer?.actor)errors.push('Independent Reviewer 与 Implementer Actor 相同');if(record.implementer?.session===record.reviewer?.session)errors.push('Independent Reviewer 与 Implementer Session 相同');}
 return{valid:errors.length===0,errors};}
const RANK={failed:0,advisory:1,passed:2};
export function reviewHasBlockingFindings(records=[]){return records.some(record=>(record.findings??[]).some(f=>f.severity==='blocking')||record.decision==='failed');}
export function reviewRequirementSatisfied(requirement,records=[],context={}){if(!requirement)return true;const minimum=requirement.minimumDecision??'passed';return records.some(record=>{const validation=validateReviewRecord(record,context);if(!validation.valid)return false;if(requirement.kind&&record.kind!==requirement.kind)return false;if(requirement.reviewer&&record.reviewer?.actor!==requirement.reviewer)return false;return(RANK[record.decision]??-1)>=(RANK[minimum]??2)&&!(record.findings??[]).some(f=>f.severity==='blocking');});}
export function reviewDigest(records=[]){return digest(records.map(r=>({id:r.id,payloadHash:r.payloadHash,decision:r.decision})));}
