import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import { spawnSync } from 'node:child_process';import test from 'node:test';import { buildContext } from '../../40-脚本/lib/context-builder.mjs';import { loadQualityContext } from '../../40-脚本/lib/quality-registry.mjs';import { gitRepo,tempDir } from '../helpers.mjs';
test('局部任务不加载 Contract 或 Canonical',t=>{const repo=gitRepo(t);const result=buildContext({cwd:repo,intent:'修复 Web 页面局部 Bug',acceptance:'行为正确'});assert.equal(result.classification.structureImpact,'local');assert.equal(result.quality.contracts.length,0);assert.equal(result.quality.exemplars.length,0);});
test('结构性任务最多加载一个主要 Contract 和 Canonical',t=>{const repo=gitRepo(t);const result=buildContext({cwd:repo,intent:'新增 Web 模块并调整架构职责',acceptance:'模块职责清楚'});assert.equal(result.classification.structureImpact,'structural');assert.equal(result.quality.contracts.length,1);assert.ok(result.quality.exemplars.length<=1);});
test('无专业能力命中的结构性任务回退通用工程契约',t=>{const repo=gitRepo(t);const result=buildContext({cwd:repo,intent:'分析当前架构和未来方向'});assert.equal(result.classification.structureImpact,'structural');assert.equal(result.quality.contracts[0]?.id,'universal-engineering');assert.ok(result.filesToRead.some(file=>file.endsWith('10-通用工程契约.md')));});
test('项目质量清单优先于底座和中央',t=>{const project=tempDir(t,'project-quality-'),template=tempDir(t,'template-quality-');for(const root of [project,template])fs.mkdirSync(path.join(root,'.ai'),{recursive:true});fs.mkdirSync(path.join(project,'docs'),{recursive:true});fs.writeFileSync(path.join(project,'docs','contract.md'),'# project contract');fs.writeFileSync(path.join(project,'docs','canonical.md'),'# project canonical');fs.writeFileSync(path.join(project,'.ai','quality.json'),JSON.stringify({contracts:[{id:'project-web',status:'active',skills:['develop-web'],roles:['web'],artifactKinds:['code'],path:'docs/contract.md'}],exemplars:[{id:'project-example',status:'active',skills:['develop-web'],artifactKinds:['code'],structureImpacts:['structural'],keywords:['模块'],read:['docs/canonical.md']}]}));fs.mkdirSync(path.join(template,'docs'),{recursive:true});fs.writeFileSync(path.join(template,'docs','contract.md'),'# template contract');fs.writeFileSync(path.join(template,'.ai','quality.json'),JSON.stringify({contracts:[{id:'template-web',status:'active',skills:['develop-web'],roles:['web'],artifactKinds:['code'],path:'docs/contract.md'}]}));const q=loadQualityContext({role:'web',intent:'新增模块',structureImpact:'structural',artifactKinds:['code'],projectRoot:project,templateRoot:template});assert.equal(q.contracts[0].source,'project');assert.equal(q.contracts[0].id,'project-web');assert.equal(q.exemplars[0].source,'project');});
test('Transient 项目读取 README、Manifest 与项目质量清单',t=>{const repo=gitRepo(t);fs.writeFileSync(path.join(repo,'package.json'),JSON.stringify({name:'app',scripts:{test:'node --test'},dependencies:{vue:'3'}}));fs.writeFileSync(path.join(repo,'.ai','quality.json'),JSON.stringify({contracts:[]}));const result=buildContext({cwd:repo,intent:'新增 Web 模块',acceptance:'行为正确'});assert.ok(result.filesToRead.some(file=>file.endsWith('README.md')));assert.ok(result.manifests.some(x=>x.kind==='node'));assert.ok(result.facts.some(x=>x.path.endsWith(path.join('.ai','quality.json'))));});
test('项目根唯一模块显式绑定模板并只加载命中资料',t=>{const project=gitRepo(t),template=gitRepo(t),modulePath=path.join(project,'web');fs.mkdirSync(modulePath,{recursive:true});fs.writeFileSync(path.join(modulePath,'AGENTS.md'),'# web');for(const [root,remote] of [[project,'https://example.com/org/project.git'],[template,'https://example.com/org/template.git']]){const result=spawnSync('git',['-C',root,'remote','add','origin',remote],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);}fs.writeFileSync(path.join(template,'AGENTS.md'),'# template');fs.writeFileSync(path.join(template,'package.json'),JSON.stringify({name:'template'}));fs.mkdirSync(path.join(template,'.ai'),{recursive:true});fs.mkdirSync(path.join(template,'docs'),{recursive:true});fs.writeFileSync(path.join(template,'docs','table.md'),'# table');fs.writeFileSync(path.join(template,'docs','dialog.md'),'# dialog');fs.writeFileSync(path.join(template,'.ai','manifest.json'),JSON.stringify({routes:[{keywords:['表格'],read:['docs/table.md']},{keywords:['弹窗'],read:['docs/dialog.md']}]}));const registry={templates:{schemaVersion:1,templates:[{id:'web-template',role:'web',enabled:true,repository:{canonicalRemote:'example.com/org/template',allowedRemotes:[]},localPathKey:'template.web',entrypoints:{agents:'AGENTS.md',manifest:'package.json'},knowledge:{mode:'in-repo',root:'.ai',manifest:'.ai/manifest.json'},quality:{manifest:'.ai/quality.json'}}]},projects:{schemaVersion:1,projects:[{id:'project',enabled:true,localPathKey:'project',entrypoints:{agents:'AGENTS.md'},modules:[{id:'project-web',role:'web',localPathKey:'project.web',canonicalRemote:'example.com/org/project',subpath:'web',templateId:'web-template'}]}]},localPaths:{project, 'project.web':modulePath,'template.web':template}};const result=buildContext({cwd:project,intent:'修复网页表格',acceptance:'行为正确',registry});assert.equal(result.context.module.id,'project-web');assert.equal(result.context.template.id,'web-template');assert.ok(result.filesToRead.some(file=>file.endsWith(path.join('docs','table.md'))),JSON.stringify(result.filesToRead));assert.ok(!result.filesToRead.some(file=>file.endsWith(path.join('docs','dialog.md'))));});

function addRemote(repository, remote) {
 const result = spawnSync('git', ['-C', repository, 'remote', 'add', 'origin', remote], { encoding: 'utf8' });
 assert.equal(result.status, 0, result.stderr);
}

test('项目说明入口不能越出项目目录', (t) => {
 const project = gitRepo(t); const modulePath = path.join(project, 'web');
 fs.mkdirSync(modulePath, { recursive: true }); addRemote(project, 'https://example.com/org/project.git');
 const registry = {
  templates: { schemaVersion: 1, templates: [] },
  projects: { schemaVersion: 1, projects: [{ id: 'project', enabled: true, localPathKey: 'project', entrypoints: { agents: 'AGENTS.md', docs: '../outside.md' }, modules: [{ id: 'project-web', role: 'web', localPathKey: 'project.web', canonicalRemote: 'example.com/org/project', subpath: 'web' }] }] },
  localPaths: { project, 'project.web': modulePath }
 };
 assert.throws(() => buildContext({ cwd: project, intent: '检查网页', registry }), /项目说明路径无效/u);
});

test('直接模块入口仍校验绑定模板身份', (t) => {
 const project = gitRepo(t); const wrongTemplate = gitRepo(t); const modulePath = path.join(project, 'web');
 fs.mkdirSync(modulePath, { recursive: true });
 addRemote(project, 'https://example.com/org/project.git'); addRemote(wrongTemplate, 'https://example.com/org/wrong-template.git');
 const registry = {
  templates: { schemaVersion: 1, templates: [{ id: 'web-template', role: 'web', enabled: true, repository: { canonicalRemote: 'example.com/org/template', allowedRemotes: [] }, localPathKey: 'template.web', entrypoints: { agents: 'AGENTS.md', manifest: 'package.json' } }] },
  projects: { schemaVersion: 1, projects: [{ id: 'project', enabled: true, localPathKey: 'project', entrypoints: { agents: 'AGENTS.md' }, modules: [{ id: 'project-web', role: 'web', localPathKey: 'project.web', canonicalRemote: 'example.com/org/project', subpath: 'web', templateId: 'web-template' }] }] },
  localPaths: { project, 'project.web': modulePath, 'template.web': wrongTemplate }
 };
 assert.throws(() => buildContext({ cwd: modulePath, intent: '检查网页', registry }), /模板身份冲突/u);
});
