import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import { spawnSync } from 'node:child_process';import test from 'node:test';import { captureBaseline,computeChangeSet,inspectPackageManifestChanges,normalizeScope,normalizeScopes,assertChangeSetWithinScope,userChangesRemainIsolated } from '../../40-脚本/lib/git-state.mjs';import { gitRepo,tempDir } from '../helpers.mjs';
test('Baseline 后只计算任务新增变化',t=>{const repo=gitRepo(t);const baseline=captureBaseline(repo);fs.writeFileSync(path.join(repo,'target.txt'),'changed\n');const c=computeChangeSet(baseline);assert.deepEqual(c.files.map(x=>x.path),['target.txt']);});
test('Semantic Fingerprint 只绑定文件语义，不因提交或空提交改变',t=>{const repo=gitRepo(t),baseline=captureBaseline(repo),target=path.join(repo,'target.txt');fs.writeFileSync(target,'semantic change\n');const uncommitted=computeChangeSet(baseline);assert.match(uncommitted.semanticFingerprint,/^[a-f0-9]{64}$/u);for(const args of [['add','target.txt'],['-c','user.email=test@example.com','-c','user.name=AI R&D OS Test','commit','-m','semantic change']])assert.equal(spawnSync('git',['-C',repo,...args],{encoding:'utf8'}).status,0);const committed=computeChangeSet(baseline);assert.equal(committed.semanticFingerprint,uncommitted.semanticFingerprint);assert.notEqual(committed.fingerprint,uncommitted.fingerprint);assert.equal(spawnSync('git',['-C',repo,'-c','user.email=test@example.com','-c','user.name=AI R&D OS Test','commit','--allow-empty','-m','empty head change'],{encoding:'utf8'}).status,0);const emptyCommit=computeChangeSet(baseline);assert.equal(emptyCommit.semanticFingerprint,committed.semanticFingerprint);assert.notEqual(emptyCommit.fingerprint,committed.fingerprint);});
test('Scope 相对目标解析、越界和符号链接逃逸被拒绝',t=>{const repo=gitRepo(t),outside=tempDir(t,'outside-');fs.mkdirSync(path.join(repo,'allowed'));const scope=normalizeScope(repo,'allowed',repo);const baseline=captureBaseline(repo);fs.writeFileSync(path.join(repo,'outside.txt'),'x');assert.throws(()=>assertChangeSetWithinScope(computeChangeSet(baseline),scope),/越出授权范围/);assert.throws(()=>normalizeScope(repo,'../outside',repo),/必须位于/);try{fs.symlinkSync(outside,path.join(repo,'link'),'dir');assert.throws(()=>normalizeScope(repo,'link',repo),/符号链接/);}catch(error){if(!['EPERM','EACCES'].includes(error.code))throw error;}});
test('重复 Scope 精确授权多个路径并拒绝逗号或 glob',t=>{const repo=gitRepo(t);for(const item of ['src','test'])fs.mkdirSync(path.join(repo,item));const scopes=normalizeScopes(repo,['src','test','src'],repo);assert.deepEqual(scopes.map(item=>item.path),['src','test']);const baseline=captureBaseline(repo);fs.writeFileSync(path.join(repo,'src','a.js'),'a');fs.writeFileSync(path.join(repo,'test','a.test.js'),'t');assert.equal(assertChangeSetWithinScope(computeChangeSet(baseline),scopes).ok,true);fs.writeFileSync(path.join(repo,'outside.txt'),'x');assert.throws(()=>assertChangeSetWithinScope(computeChangeSet(baseline),scopes),/outside\.txt/u);assert.throws(()=>normalizeScope(repo,['src','test'],repo),/只能指定一个路径.*重复传入 --scope/u);assert.throws(()=>normalizeScopes(repo,'src,test',repo),/不接受逗号拼接.*重复传入 --scope/u);assert.throws(()=>normalizeScopes(repo,'src\/**',repo),/不支持 glob.*明确路径/u);});
test('package.json 真实差异区分元数据与运行契约',t=>{const repo=gitRepo(t);fs.writeFileSync(path.join(repo,'package.json'),JSON.stringify({name:'demo',version:'1.0.0',scripts:{test:'node --test'},dependencies:{}}));for(const args of [['add','package.json'],['-c','user.email=t@e.c','-c','user.name=T','commit','-m','manifest']]){const result=spawnSync('git',['-C',repo,...args],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);}const metadataBaseline=captureBaseline(repo);fs.writeFileSync(path.join(repo,'package.json'),JSON.stringify({name:'demo',version:'1.0.1',scripts:{test:'node --test'},dependencies:{}}));const metadata=inspectPackageManifestChanges(metadataBaseline,computeChangeSet(metadataBaseline));assert.equal(metadata[0].metadataOnly,true);assert.deepEqual(metadata[0].changedFields,['version']);fs.writeFileSync(path.join(repo,'package.json'),JSON.stringify({name:'demo',version:'1.0.0',scripts:{test:'node --test','test:all':'node --test all'},dependencies:{}}));const runtime=inspectPackageManifestChanges(metadataBaseline,computeChangeSet(metadataBaseline));assert.equal(runtime[0].metadataOnly,false);assert.equal(runtime[0].requiresPackageIntegrity,true);assert.deepEqual(runtime[0].changedFields,['scripts']);});
test('默认保护准备前用户已有改动，可显式授权同路径',t=>{const repo=gitRepo(t);fs.writeFileSync(path.join(repo,'README.md'),'user change\n');const baseline=captureBaseline(repo);fs.writeFileSync(path.join(repo,'README.md'),'task change\n');const c=computeChangeSet(baseline);assert.equal(userChangesRemainIsolated(baseline,c).ok,false);assert.equal(userChangesRemainIsolated(baseline,c,['README.md']).ok,true);});
test('Git 状态无法确认时 Baseline 和 ChangeSet 都严格失败',t=>{
  const baselineRepo=gitRepo(t),baselineGit=path.join(baselineRepo,'.git');
  fs.renameSync(baselineGit,`${baselineGit}-disabled`);
  assert.throws(()=>captureBaseline(baselineRepo),/Git 状态无法确认.*status/u);

  const changeRepo=gitRepo(t),baseline=captureBaseline(changeRepo),changeGit=path.join(changeRepo,'.git');
  fs.renameSync(changeGit,`${changeGit}-disabled`);
  assert.throws(()=>computeChangeSet(baseline),/Git 状态无法确认.*status/u);
});
