import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import { spawn } from 'node:child_process';import test from 'node:test';import { createTask,readTask,updateTask,readHistory } from '../../40-脚本/lib/state-manager.mjs';import { tempDir } from '../helpers.mjs';
function create(stateRoot,id='task-state',gitRoot=null){return createTask({stateRoot,taskId:id,goal:{summary:'x'},acceptance:[],authorization:{scope:[],externalActions:[]},classification:{controlMode:'quick',structureImpact:'none',continuity:'tracked',artifactKinds:['documentation']},context:{},baseline:gitRoot?{gitRoot}:null,verification:{budget:{mode:'quick',limitMs:1000,spentMs:0},inputCycle:0}});}
test('非法状态转换和非用户 accepted 被阻止',t=>{const root=tempDir(t);create(root);assert.throws(()=>updateTask({stateRoot:root,taskId:'task-state',expectedRevision:1,transitionTo:'accepted',event:'delivery'}),/accepted 只能|非法状态/);});
test('用户验收事件可以归档',t=>{const root=tempDir(t);create(root);updateTask({stateRoot:root,taskId:'task-state',expectedRevision:1,transitionTo:'waiting_acceptance',event:'delivery'});const done=updateTask({stateRoot:root,taskId:'task-state',expectedRevision:2,transitionTo:'accepted',event:'user-accept'});assert.equal(done.task.status,'accepted');assert.equal(readHistory({stateRoot:root}).length,1);});
test('等待验收后的输入变化可以回到重新验证',t=>{const root=tempDir(t);create(root);updateTask({stateRoot:root,taskId:'task-state',expectedRevision:1,transitionTo:'waiting_acceptance',event:'delivery'});const reopened=updateTask({stateRoot:root,taskId:'task-state',expectedRevision:2,transitionTo:'verifying',event:'delivery'});assert.equal(reopened.task.status,'verifying');});
test('Revision 冲突被阻止',t=>{const root=tempDir(t);create(root);updateTask({stateRoot:root,taskId:'task-state',expectedRevision:1,transitionTo:'saved',event:'save'});assert.throws(()=>updateTask({stateRoot:root,taskId:'task-state',expectedRevision:1,transitionTo:'implementing',event:'resume'}),/版本冲突/);});
test('进程锁避免两个同 Revision 更新同时成功',async t=>{const root=tempDir(t);create(root,'task-concurrent');const helper=path.join(root,'writer.mjs'),barrier=path.join(root,'go');const modulePath=path.resolve('40-脚本/lib/state-manager.mjs').replaceAll('\\','/');fs.writeFileSync(helper,`import fs from 'node:fs'; import { updateTask } from 'file://${modulePath}'; const wait=new Int32Array(new SharedArrayBuffer(4)); while(!fs.existsSync(process.argv[3])) Atomics.wait(wait,0,0,5); try { updateTask({stateRoot:process.argv[2],taskId:'task-concurrent',expectedRevision:1,transitionTo:'saved',event:'save',mutate(task){Atomics.wait(wait,0,0,50);return task;}}); console.log('ok'); } catch(e){ console.log('blocked'); }`);const run=()=>new Promise((resolve,reject)=>{const child=spawn(process.execPath,[helper,root,barrier],{stdio:['ignore','pipe','pipe']});let out='',err='';child.stdout.on('data',d=>out+=d);child.stderr.on('data',d=>err+=d);child.on('error',reject);child.on('close',code=>code===0?resolve(out.trim()):reject(new Error(err)));});const a=run(),b=run();await new Promise(r=>setTimeout(r,30));fs.writeFileSync(barrier,'go');const results=(await Promise.all([a,b])).sort();assert.deepEqual(results,['blocked','ok']);assert.equal(readTask({stateRoot:root,taskId:'task-concurrent'}).task.stateRevision,2);});
test('所有非写态进入写态前统一检查工作树冲突',t=>{for(const [status,target,event] of [['waiting_acceptance','needs_rework','user-reject'],['saved','verifying','resume'],['blocked','implementing','resume']]){const root=tempDir(t),gitRoot=path.join(root,'repo'),oldId=`task-old-${status}`,currentId=`task-current-${status}`;create(root,oldId,gitRoot);updateTask({stateRoot:root,taskId:oldId,expectedRevision:1,transitionTo:status,event:status==='saved'?'save':'delivery'});create(root,currentId,gitRoot);assert.throws(()=>updateTask({stateRoot:root,taskId:oldId,expectedRevision:2,transitionTo:target,event}),new RegExp(currentId,'u'));assert.equal(readTask({stateRoot:root,taskId:oldId}).task.status,status);}});
test('needs_rework 保存后释放工作树且恢复时重新竞争',t=>{const root=tempDir(t),gitRoot=path.join(root,'repo'),oldId='task-old-rework',currentId='task-current-writing';create(root,oldId,gitRoot);updateTask({stateRoot:root,taskId:oldId,expectedRevision:1,transitionTo:'needs_rework',event:'delivery'});updateTask({stateRoot:root,taskId:oldId,expectedRevision:2,transitionTo:'saved',event:'save'});create(root,currentId,gitRoot);assert.throws(()=>updateTask({stateRoot:root,taskId:oldId,expectedRevision:3,transitionTo:'implementing',event:'resume'}),new RegExp(currentId,'u'));assert.equal(readTask({stateRoot:root,taskId:oldId}).task.status,'saved');});
