import assert from 'node:assert/strict';import test from 'node:test';import { classifyTask,reclassifyFromChangeSet,determineEvidenceRequirements,evaluateDeliveryEligibility,canRerunVerification } from '../../40-脚本/lib/task-policy.mjs';
test('Intent 风险只初分，真实非风险文档 ChangeSet 可回到 Quick',()=>{const initial=classifyTask({intent:'更新权限说明文档',acceptance:'说明准确'});assert.equal(initial.controlMode,'controlled');const actual=reclassifyFromChangeSet(initial,{files:[{path:'README.md'}]});assert.equal(actual.controlMode,'quick');});
test('纯文档 ChangeSet 按真实属性进入 Quick，验收措辞不误判为需求',()=>{const initial=classifyTask({intent:'更新入口规则',acceptance:'规则满足验收条件'});assert.equal(initial.controlMode,'standard');assert.deepEqual(initial.artifactKinds,['code']);const actual=reclassifyFromChangeSet(initial,{files:[{path:'AGENTS.md'}]});assert.equal(actual.controlMode,'quick');assert.equal(actual.structureImpact,'none');assert.deepEqual(actual.artifactKinds,['documentation']);assert.equal(determineEvidenceRequirements({classification:actual,changeSet:{files:[{path:'AGENTS.md'}]},acceptance:[]}).includes('behavior'),false);});
test('需求或结构性文档保持 Standard',()=>{for(const intent of ['更新需求规格文档','更新架构说明并重构体系']){const initial=classifyTask({intent,acceptance:'内容准确'});assert.equal(initial.controlMode,'standard');const actual=reclassifyFromChangeSet(initial,{files:[{path:'docs/spec.md'}]});assert.equal(actual.controlMode,'standard');}});
test('真实 Auth ChangeSet 升级 Controlled',()=>{const initial=classifyTask({intent:'修改普通功能'});assert.equal(reclassifyFromChangeSet(initial,{files:[{path:'src/auth/permission.ts'}]}).controlMode,'controlled');});
test('UI 文件不自动要求 Browser',()=>{const covers=determineEvidenceRequirements({classification:{controlMode:'standard',structureImpact:'local',artifactKinds:['ui']},changeSet:{files:[{path:'page.vue'}]},acceptance:[],observableBrowserBehavior:false});assert.equal(covers.includes('browser'),false);assert.equal(covers.includes('typecheck'),true);});
test('交付门禁区分缺失 Evidence 与 Review',()=>{const base={identityValid:true,scopeValid:true,userChangesIsolated:true,blockers:[],invalidEvidence:[],missingAcceptance:[],missingCovers:[]};assert.equal(evaluateDeliveryEligibility(base).decision,'waiting_acceptance');assert.equal(evaluateDeliveryEligibility({...base,missingAcceptance:['A1']}).decision,'verifying');assert.equal(evaluateDeliveryEligibility({...base,explicitReviewRequirement:{kind:'independent-agent'},reviewSatisfied:false}).decision,'reviewing');});
test('需要集成的任务先形成提交再进入待集成',()=>{const base={identityValid:true,scopeValid:true,userChangesIsolated:true,blockers:[],invalidEvidence:[],missingAcceptance:[],missingCovers:[],integrationRequired:true};assert.equal(evaluateDeliveryEligibility({...base,integrationReady:false,integrationReasons:['uncommitted-task-changes']}).decision,'verifying');assert.equal(evaluateDeliveryEligibility({...base,integrationReady:true}).decision,'ready_to_integrate');});
test('相同输入失败只允许一次诊断重试',()=>{assert.equal(canRerunVerification({previousFailure:true}).allowed,false);assert.equal(canRerunVerification({previousFailure:true,diagnosticRetry:true,diagnosticRetryUsed:false}).allowed,true);assert.equal(canRerunVerification({previousFailure:true,diagnosticRetry:true,diagnosticRetryUsed:true}).allowed,false);});
